
dev-hubs-web:
  enabled: true
  nameOverride: dev-hubs-web

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment

    #livenessProbe:
    #  httpGet:
    #    path: /v1/api/Authorization/HealthCheck
    #    port: 8080
    #  initialDelaySeconds: 20
    #  periodSeconds: 5

    image:
      name: asia-southeast1-docker.pkg.dev/its-artifact-commons/dev-hubs/dev-hubs-web

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 5000
        protocol: TCP
        name: http
