
onix-web-scan:
  enabled: true
  nameOverride: onix-web-scan

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment

    #livenessProbe:
    #  httpGet:
    #    path: /v1/api/Authorization/HealthCheck
    #    port: 8080
    #  initialDelaySeconds: 20
    #  periodSeconds: 5

    image:
      name: asia-southeast1-docker.pkg.dev/its-artifact-commons/onix-v2/onix-v2-web-scan

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 5000
        protocol: TCP
        name: http
