please-protect-portal:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: DUMMY
        value: "001"

      - name: NEXT_PUBLIC_CONSOLE_URL
        value: 'https://center.please-protect.com'
