---
envAlias: production
envAliasJob: Production
domainOnixAPI: api.please-scan.com
domainOnixScan: scan.please-scan.com
envGroup: prod
onixWebScanPath: verify
onixWebScanStaticPath: scan-static
onixWebScanDomain: verify.please-scan.com
onixConsoleDomain: console.please-scan.com
onixRegisterDomain: register.please-scan.com
onixAdminDomain: admin.please-scan.com

pleaseScanWebDomain: please-scan.com
devHubsWebDomain: dev-hubs.com

pgDiskSize: 100Gi
