---
envAlias: development
domainOnixAPI: scan-dev.please-scan.com
domainOnixScan: scan-dev.please-scan.com
envGroup: dev
onixWebScanPath: verify
onixWebScanStaticPath: scan-static
onixWebScanDomain: verify-dev.please-scan.com

pleaseScanWebDomain: web-dev.please-scan.com
