---
envAlias: development
domainOnixAPI: aldamex-dev.please-scan.com
envGroup: dev
onixWebScanPath: verify
onixWebScanStaticPath: scan-static
onixWebScanDomain: aldamex-web-dev.please-scan.com

pleaseScanWebDomain: web-dev.please-scan.com
