---
envAlias: development
envAliasJob: Development
domainOnixAPI: api-dev.please-scan.com
domainOnixScan: scan-dev.please-scan.com
envGroup: dev
onixWebScanPath: verify
onixWebScanStaticPath: scan-static
onixWebScanDomain: verify-dev.please-scan.com
onixConsoleDomain: console-dev.please-scan.com

pleaseScanWebDomain: web-dev.please-scan.com
devHubsWebDomain: web-dev.dev-hubs.com
