---
envAlias: production
domainOnixAPI: aldamex.please-scan.com
envGroup: prod
onixWebScanPath: verify
onixWebScanStaticPath: scan-static
onixWebScanDomain: aldamex.com

pleaseScanWebDomain: please-scan.com
