---
envAlias: production
domainOnixAPI: scan.please-scan.com
envGroup: prod
onixWebScanPath: verify
onixWebScanStaticPath: scan-static
onixWebScanDomain: verify.please-scan.com

pleaseScanWebDomain: please-scan.com
