apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: idp-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: idp-secret      # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: IDP_CLIENT_ID
    remoteRef:
      key: "onix-v2-idp-{{ .Values.envAlias }}"
      property: IDP_CLIENT_ID
      version: latest

  - secretKey: IDP_CLIENT_SECRET
    remoteRef:
      key: "onix-v2-idp-{{ .Values.envAlias }}"
      property: IDP_CLIENT_SECRET
      version: latest

  - secretKey: IDP_URL_PREFIX
    remoteRef:
      key: "onix-v2-idp-{{ .Values.envAlias }}"
      property: IDP_URL_PREFIX
      version: latest

  - secretKey: IDP_REALM
    remoteRef:
      key: "onix-v2-idp-{{ .Values.envAlias }}"
      property: IDP_REALM
      version: latest
