apiVersion: batch/v1
kind: CronJob
metadata:
  name: scan-item-generator
spec:
  # kubectl create job --from=cronjob/scan-item-generator scan-item-generator-001 -n onix-jobs
  suspend: true
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: cron-script
            image: asia-southeast1-docker.pkg.dev/its-artifact-commons/onix-v2/onix-v2-jobs:{{ .Values.onixJobs.imageTag }}
            imagePullPolicy: IfNotPresent
            command:
            - ruby
            args:
            - /scripts/scan-item-generator.rb
            env:
            - name: REDIS_HOST
              value: redis-master

            - name: REDIS_PORT
              value: "6379"

            - name: REDIS_PASSWORD
              value: "anything-notuse"

            - name: SCAN_ITEM_ORG
              value: {{ .Values.onixJobs.scanItemOrg }}

            - name: SCAN_ITEM_BUCKET
              value: {{ .Values.onixJobs.scanItemBucket }}

            - name: SCAN_ITEM_COUNT
              value: {{ .Values.onixJobs.scanItemCount }}

            - name: SCAN_ITEM_URL
              value: {{ .Values.onixJobs.scanItemUrl }}

            volumeMounts:
            - name: temp-dir
              mountPath: /data/temp

          restartPolicy: OnFailure

          volumes:
          - name: temp-dir
            emptyDir: {}
