kong:
  enabled: false # TODO : Will need to fix Kong crash loop back  
  fullnameOverride: kong
  proxy:
    type: ClusterIP

  dblessConfig:
    configMap: kong-config

  env:
    database: "off"
    #KONG_ADMIN_LISTEN: "0.0.0.0:8444 ssl"
    #KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"

  customEnv:
    DUMMY: "002" #Update this when Kong configuration is changed in order to restart the pods

  ingressController:
    enabled: false # This is required in DB less mode

  admin:
    enabled: false
    #type: ClusterIP
    #http:
    #  enabled: false

  volumeMounts:
    - mountPath: /kong_prefix
      name: kong-prefix

  volumes:
    - name: kong-prefix
      emptyDir: {}
