kong:
  enabled: true
  fullnameOverride: kong
  proxy:
    type: ClusterIP

  dblessConfig:
    configMap: kong-config

  env:
    database: "off"

  customEnv:
    DUMMY: "002" #Update this when Kong configuration is changed in order to restart the pods
    KONG_ADMIN_LISTEN: '127.0.0.1:8444 http2 ssl'
    KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 http2 ssl"

  ingressController:
    enabled: false # This is required in DB less mode

  admin:
    enabled: false
    #type: ClusterIP
    #http:
    #  enabled: false

  volumeMounts:
    - mountPath: /kong_prefix
      name: kong-prefix

  volumes:
    - name: kong-prefix
      emptyDir: {}
